# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3bfee37b1c9d9043173b97f986f9ef57d9181c473f1bd50102fbb9f9cdf78b27cc6db270488cf7cd761ed8689084f3ceca06eb3d64c8f3864924a3d120e5bf17

test:
  secret_key_base: 809a207886d883c2f0280af6cc941c37d12298ad7a57687c6ea1cbc78b42e055c2627075ae645881e0a8b268c500fa84006b71c70afa6becd8fc6c35f3803356

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
